### ISSUE TITLE
设置 自动滚动 后,拖动捕获列表右侧垂直滚动条无效，总是被移动到列表最后

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitor#1]
iMonitor 2.0.0

**Comment by wecooperate** [comment]
这个设计就是这样的，可以滚动的时候选择一列，如果选择的列在可视访问内，就会阻止自动滚动。

需要拖动滚动条查看列的时候，还是建议把自动滚动关闭，只有需要查看最后一条数据的时候才设置自动滚动。

**Comment by sagasm** [comment]
我忘了提了，是在停止事件捕获的情况下也无法移动垂直滚动条，自动滚动常理是添加数据后才会滚动到最后一行吧。
