### ISSUE TITLE
win7x64驱动加载失败

### ISSUE THREAD

**Issue by IULOVE** [wecooperate/iMonitor#12]
下载最新的版本，win7 x64驱动加载不了。
补丁已经安装了
![gx](https://user-images.githubusercontent.com/14193276/206834763-5a1c9260-4802-4539-b336-9db9bd5700ed.png)

![222](https://user-images.githubusercontent.com/14193276/206834818-3699a908-3f07-4de2-9d75-8f21f69795f8.png)

关闭签名验证是可以的~

**Comment by wecooperate** [comment]
因为目前的驱动证书都是SHA256的，Win7默认不支持SHA256的证书签名，需要通过安装补丁解决（某些情况安装了也可能无效）。未来这里会通过过微软认证来解决，但是会比较麻烦。
临时请先通过关闭签名的方式使用，或者自己对驱动重新签名。

**Comment by IULOVE** [comment]
> 因为目前的驱动证书都是SHA256的，Win7默认不支持SHA256的证书签名，需要通过安装补丁解决（某些情况安装了也可能无效）。未来这里会通过过微软认证来解决，但是会比较麻烦。 临时请先通过关闭签名的方式使用，或者自己对驱动重新签名。

好吧，那你有在win7测试过吗，也是不能加载？

**Comment by wecooperate** [comment]
win7测试也是开启测试签名模式测试的
