### ISSUE TITLE
列显示有问题

### ISSUE THREAD

**Issue by QQ2017** [wecooperate/iMonitor#14]
选择了很多列，但只能显示一部分
![image](https://user-images.githubusercontent.com/23667705/226892480-49c0fbb3-491b-4243-9f80-447380e8630a.png)

**Comment by wecooperate** [comment]
选择列后，如果没有新的事件或者其他触发条件，会导致列不会重新刷新，下个版本修复。
临时解决：可以选择列后切换一下其他的功能开关（比如开启关闭、快速切换、分组等等都可以触发刷新）



创信长荣科技
https://github.com/wecooperate/iMonitorSDK 

 
发件人： 27℃
发送时间： 2023-03-22 19:36
收件人： wecooperate/iMonitor
抄送： Subscribed
主题： [wecooperate/iMonitor] 列显示有问题 (Issue #14)
选择了很多列，但只能显示一部分
