### ISSUE TITLE
建议增加拖拽可执行程序监控行为

### ISSUE THREAD

**Issue by brian763** [wecooperate/iMonitor#15]
包括其进程以及其子进程和注入其他进程的线程等行为
比如和HRSword的组ID差不多

**Comment by wecooperate** [comment]
收到，下个版本看情况添加支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitor] 建议增加拖拽可执行程序监控行为 (Issue #15)




 
包括其进程以及其子进程和注入其他进程的线程等行为
 比如和HRSword的组ID差不多

**Comment by wecooperate** [comment]
拖曳其实就是启动进程，可能需要自己手动启动一下，然后再手动添加过滤。


按组过滤，可以后面在进程树添加“进程+子进程”的规则过滤。
远程线程注入，可以在进程树里面添加进程关联，把关联的进程也添加进过滤。


这样应该满足需求？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitor] 建议增加拖拽可执行程序监控行为 (Issue #15)




 
包括其进程以及其子进程和注入其他进程的线程等行为
 比如和HRSword的组ID差不多

**Comment by wecooperate** [comment]
2.5.0 版本发布
在进程列表添加进程树支持
![image](https://user-images.githubusercontent.com/63456933/229354658-4467c254-9f06-42c1-b309-4050f3b26ca7.png)
