### ISSUE TITLE
[Feature Request] 规则管理页面点击确定时提示“是否添加正在编辑的规则”

### ISSUE THREAD

**Issue by cesaryuan** [wecooperate/iMonitor#16]
感谢贵团队制作的冰境软件，比Process Monitor好用不少（更流畅易用）

但是有一个小细节Process Monitor做的比较好，就是在编辑规则的时候，如果没有Add正在编辑的规则就直接点击确定的话，Procmon会有以下提示`You did not add the item you were editing. Add it now?`

![image](https://user-images.githubusercontent.com/35998162/237029571-5d733c9d-496f-429d-a2e5-5a45d1c84572.png)

希望冰镜可以改进这一点，因为经常忘记Add规则就直接点击确定，导致白编辑了哈哈

**Comment by wecooperate** [comment]
感谢反馈，下个版本优化



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月9日(周二) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitor] [Feature Request] 规则管理页面点击确定时提示“是否添加正在编辑的规则” (Issue #16)




 
感谢贵团队制作的冰境软件，比Process Monitor好用不少（更流畅易用）
 
但是有一个小细节Process Monitor做的比较好，就是在编辑规则的时候，如果没有Add正在编辑的规则就直接点击确定的话，Procmon会有以下提示You did not add the item you were editing. Add it now?
 

 
希望冰镜可以改进这一点，因为经常忘记Add规则就直接点击确定，导致白编辑了哈哈

**Comment by wecooperate** [comment]
2.5.2 版本发布，已经添加支持
