### ISSUE TITLE
建议：分组详情窗口

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitor#2]
该窗口用于展示与分组 count对应行数的未分组前各行数据。

**Comment by wecooperate** [comment]
这个下个版本排期支持。

一般经过分组了，被隐藏的数据跟当前显示基本是一样的。某些场景需要查看分组前的数据的话，可以临时通过设置当前分组的过滤规则来显示。

**Comment by sagasm** [comment]
这个需求来源于程序运行找不到dll或者编译程序找不到源文件，这个时候分析各个查找路径还是比较重要的，此时配合一个文件名列就很有用了：
![iMonitor_SPNL9My2eb](https://user-images.githubusercontent.com/14829950/191283517-db18f74f-f553-46ab-bb4a-647f311cdb1d.png)

**Comment by wecooperate** [comment]
dll分析2.1.0版本已经支持，可以更新版本体验
