### ISSUE TITLE
一直弹出证书错误

### ISSUE THREAD

**Issue by cesaryuan** [wecooperate/iMonitor#20]
![image](https://github.com/wecooperate/iMonitor/assets/35998162/00ee486e-34ab-410a-b4ee-a58058cfaec9)

如上图，关掉后还是会弹出，点击查看证书：

![image](https://github.com/wecooperate/iMonitor/assets/35998162/438cb04e-5e2e-4642-8819-2bf6beb8ca31)

**Comment by wecooperate** [comment]
关闭HTTP监控就好了，因为HTTP监控为了解析HTTPS的内容，会有本地的CA证书

**Comment by wecooperate** [comment]
![image](https://github.com/wecooperate/iMonitor/assets/63456933/7814a51e-97ca-4cc5-ac42-f3b50f705054)

**Comment by cesaryuan** [comment]
> 关闭HTTP监控就好了，因为HTTP监控为了解析HTTPS的内容，会有本地的CA证书

谢谢，可以了
