### ISSUE TITLE
建议：未分组列可设置为显示最后一条记录的结果或支持按某列排序

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitor#4]
用途：如 Result 列设为显示显示最后一条记录的结果，可用于快速判断一个dll是否查找成功：
![image](https://user-images.githubusercontent.com/14829950/191628192-380d8955-1f98-46ca-b0e2-81c95dcfd272.png)
目前只能把Result列也分组，查看不在一起的两条记录，不太方便。也可以支持按列排序来解决这个问题。

**Comment by wecooperate** [comment]
排序开始是支持的，但是在数据量比较大的时候，存在性能问题，后面排序功能就去掉了

【计划中】后面会添加专门针对DLL找不到、DLL挟持分析的支持

**Comment by sagasm** [comment]
请问能否恢复排序功能，比如像有的软件一样，记录超过多少条提示排序时间可能过长。毕竟记录多的时候，用户可以自己考虑添加过滤器减少数据。毕竟排序功能有时候还是很有用的。

**Comment by RedConda** [comment]
大哥能给个联系方式吗？

**Comment by RedConda** [comment]
> 请问能否恢复排序功能，比如像有的软件一样，记录超过多少条提示排序时间可能过长。毕竟记录多的时候，用户可以自己考虑添加过滤器减少数据。毕竟排序功能有时候还是很有用的。

大哥能给个联系方式吗？

**Comment by wecooperate** [comment]
> 请问能否恢复排序功能，比如像有的软件一样，记录超过多少条提示排序时间可能过长。毕竟记录多的时候，用户可以自己考虑添加过滤器减少数据。毕竟排序功能有时候还是很有用的。

我重新实现排序的逻辑，然后看看效果，合适的话就下个版本添加

**Comment by wecooperate** [comment]
联系方式可以通过 https://imonitorsdk.com/about 获取

**Comment by wecooperate** [comment]
添加快照的功能，快照支持排序。
添加Dll丢失、挟持分析功能。
请更新到2.1.0版本体验
