### ISSUE TITLE
查找时崩溃

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitor#5]
iMonitor v2.0:
![image](https://user-images.githubusercontent.com/14829950/193966567-38bdc8ec-f214-4945-b2ec-bff4cdb75e99.png)

**Comment by wecooperate** [comment]
麻烦将dump（C:\ProgramData\iMonitor\crash 下面）发送到admin@imonitorsdk.com

**Comment by wecooperate** [comment]
2.1修复，同之前的几个反馈一起更新

**Comment by wecooperate** [comment]
已经修复，请更新到2.1.0版本
