### ISSUE TITLE
"丢弃被过滤事件"开关的疑问

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitor#7]
使用中发现“丢弃被过滤事件”开关不会考虑以下5个开关的状态：

![](https://user-images.githubusercontent.com/14829950/194237061-626e87c8-f66a-4845-804b-c931750bdc06.png)

**Comment by wecooperate** [comment]
是的，这几个属于快速过滤，不会被丢弃












iMonitor
***@***.***

人因梦想而伟大

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 下午3:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitor] "丢弃被过滤事件"开关的疑问 (Issue #7)




 
使用中发现“丢弃被过滤事件”开关不会考虑以下5个开关的状态：
