### ISSUE TITLE
[bug] 记录添加列时crash

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitor#8]
![image](https://user-images.githubusercontent.com/14829950/194475778-848a51cd-9fed-4425-bb56-dc2f14e6d3bc.png)

**Comment by wecooperate** [comment]
下个版本修复 （添加支持快照功能的时候，选择列适配快照模式后引起的BUG）

**Comment by wecooperate** [comment]
2.1.1 版本已经修复，请更新到最新的版本
